name: Build game

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GODOT_VERSION: 4.7.1.stable # Set your Godot version (e.g., 4.2.2.stable, 3.5.3.stable)
  EXPORT_NAME: Quarto        # The name of your output binary/files

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      # Use the godot-ci Docker image matching your Godot version
      image: barichello/godot-ci:${{ env.GODOT_VERSION }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Build Directory
        run: mkdir -v -p build/web

      - name: Export Web
        run: godot --headless --export-release "HTML5" build/web/index.html

      - name: Upload Web Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-export
          path: build/web